sonar.projectKey=schnappy-platform
sonar.projectName=Schnappy Platform
sonar.sources=helm/schnappy,helm/schnappy-data,helm/schnappy-auth,helm/schnappy-observability,helm/schnappy-sonarqube,scylla,kafka,apt-cache,grafana
sonar.sourceEncoding=UTF-8
