sonar.projectKey=schnappy-infrastructure
sonar.projectName=Schnappy Infrastructure
sonar.sources=helm/templates,helm/values.yaml,helm/Chart.yaml,scylla,kafka,apt-cache,grafana
sonar.sourceEncoding=UTF-8
