{{- if and .Values.prometheus.enabled (eq (.Values.alertmanager.enabled | toString) "true") (not .Values.alertmanager.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monitor.alertmanager.secretName" . }}
  labels:
    {{- include "monitor.alertmanager.labels" . | nindent 4 }}
type: Opaque
stringData:
  ALERTMANAGER_WEBHOOK_SECRET: {{ .Values.alertmanager.webhookSecret | quote }}
{{- end }}
