apiVersion: v1
kind: Service
metadata:
  name: {{ include "monitor.app.serviceName" . }}
  labels:
    {{- include "monitor.app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "monitor.app.selectorLabels" . | nindent 4 }}
