{{- if and .Values.auth.jwtSecret (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monitor.auth.secretName" . }}
  labels:
    {{- include "monitor.app.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.auth.jwtSecret | quote }}
{{- end }}
