{{- if eq (.Values.chessService.enabled | toString) "true" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "schnappy.chess.serviceName" . }}
  labels:
    {{- include "schnappy.chess.labels" . | nindent 4 }}
spec:
  type: {{ .Values.chessService.service.type }}
  ports:
    - port: {{ .Values.chessService.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "schnappy.chess.selectorLabels" . | nindent 4 }}
{{- end }}
