{{- if and (eq (.Values.elk.enabled | toString) "true") .Values.elk.elasticsearch.password (not .Values.elk.elasticsearch.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monitor.elasticsearch.secretName" . }}
  labels:
    {{- include "monitor.elasticsearch.labels" . | nindent 4 }}
type: Opaque
stringData:
  ELASTICSEARCH_PASSWORD: {{ .Values.elk.elasticsearch.password | quote }}
  KIBANA_PASSWORD: {{ .Values.elk.elasticsearch.password | quote }}
{{- end }}
