{{- if eq (.Values.elk.enabled | toString) "true" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "schnappy.fullname" . }}-fluentbit
  labels:
    {{- include "schnappy.fluentbit.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "schnappy.fluentbit.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "schnappy.fluentbit.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "schnappy.fullname" . }}-fluentbit
      securityContext:
        runAsUser: 0
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: fluent-bit
          image: {{ .Values.elk.fluentbit.image }}
          env:
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "schnappy.elasticsearch.secretName" . }}
                  key: ELASTICSEARCH_PASSWORD
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: config
              mountPath: /fluent-bit/etc/fluent-bit.conf
              subPath: fluent-bit.conf
            - name: parsers
              mountPath: /fluent-bit/etc/parsers.conf
              subPath: parsers.conf
            - name: varlogcontainers
              mountPath: /var/log/containers
              readOnly: true
            - name: varlogpods
              mountPath: /var/log/pods
              readOnly: true
            - name: db
              mountPath: /fluent-bit/db
          resources:
            {{- toYaml .Values.elk.fluentbit.resources | nindent 12 }}
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
              add:
                - DAC_READ_SEARCH
      volumes:
        - name: config
          configMap:
            name: {{ include "schnappy.fullname" . }}-fluentbit-config
        - name: parsers
          configMap:
            name: {{ include "schnappy.fullname" . }}-fluentbit-config
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: db
          emptyDir: {}
      tolerations:
        - effect: NoSchedule
          operator: Exists
{{- end }}
