{{- if .Values.frontend.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "monitor.frontend.serviceName" . }}
  labels:
    {{- include "monitor.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "monitor.frontend.selectorLabels" . | nindent 4 }}
{{- end }}
