{{- if and .Values.game.enabled .Values.app.ingress.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "schnappy.fullname" . }}-game-strip
  labels:
    {{- include "schnappy.game-scp.labels" . | nindent 4 }}
spec:
  stripPrefix:
    prefixes:
      - /game
{{- end }}
