{{- if .Values.game.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "schnappy.game-scp.serviceName" . }}
  labels:
    {{- include "schnappy.game-scp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.game.service.type }}
  ports:
    - port: {{ .Values.game.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "schnappy.game-scp.selectorLabels" . | nindent 4 }}
{{- end }}
