{{- if and .Values.game.enabled .Values.app.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "schnappy.fullname" . }}-game
  labels:
    {{- include "schnappy.game-scp.labels" . | nindent 4 }}
  annotations:
    {{- if and .Values.app.ingress.tls .Values.app.ingress.tls.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.app.ingress.tls.clusterIssuer | default "letsencrypt-prod" }}
    {{- end }}
spec:
  {{- if .Values.app.ingress.className }}
  ingressClassName: {{ .Values.app.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.app.ingress.host }}
      http:
        paths:
          - path: /game
            pathType: Prefix
            backend:
              service:
                name: {{ include "schnappy.game-scp.serviceName" . }}
                port:
                  number: {{ .Values.game.service.port }}
  {{- if and .Values.app.ingress.tls .Values.app.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.app.ingress.host }}
      secretName: {{ .Values.app.ingress.tls.secretName | default (printf "%s-tls" (include "schnappy.fullname" .)) }}
  {{- end }}
{{- end }}
