{{- if eq (.Values.gateway.enabled | toString) "true" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "monitor.gateway.serviceName" . }}
  labels:
    {{- include "monitor.gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - port: {{ .Values.gateway.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "monitor.gateway.selectorLabels" . | nindent 4 }}
{{- end }}
