{{- if and (eq (.Values.elk.enabled | toString) "true") .Values.elk.kibana.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "monitor.fullname" . }}-kibana
  labels:
    {{- include "monitor.kibana.labels" . | nindent 4 }}
  {{- if and .Values.elk.kibana.ingress.tls .Values.elk.kibana.ingress.tls.enabled }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.elk.kibana.ingress.tls.clusterIssuer | default "letsencrypt-prod" }}
  {{- end }}
spec:
  {{- if .Values.elk.kibana.ingress.className }}
  ingressClassName: {{ .Values.elk.kibana.ingress.className }}
  {{- end }}
  {{- if and .Values.elk.kibana.ingress.tls .Values.elk.kibana.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.elk.kibana.ingress.host }}
      {{- if .Values.elk.kibana.ingress.tls.secretName }}
      secretName: {{ .Values.elk.kibana.ingress.tls.secretName }}
      {{- end }}
  {{- end }}
  rules:
    - {{ if .Values.elk.kibana.ingress.host }}host: {{ .Values.elk.kibana.ingress.host }}{{ end }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "monitor.kibana.serviceName" . }}
                port:
                  number: 5601
{{- end }}
