{{- if and .Values.prometheus.enabled (eq (.Values.kubeStateMetrics.enabled | toString) "true") -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "monitor.kubeStateMetrics.serviceName" . }}
  labels:
    {{- include "monitor.kubeStateMetrics.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "monitor.kubeStateMetrics.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "monitor.kubeStateMetrics.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "monitor.fullname" . }}-kube-state-metrics
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: kube-state-metrics
          image: {{ .Values.kubeStateMetrics.image }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          args:
            - '--port=8080'
            - '--telemetry-port=8081'
          ports:
            - containerPort: 8080
              name: metrics
            - containerPort: 8081
              name: telemetry
          resources:
            {{- toYaml .Values.kubeStateMetrics.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
{{- end }}
