{{- if and .Values.mail.password (not .Values.mail.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monitor.mail.secretName" . }}
  labels:
    {{- include "monitor.app.labels" . | nindent 4 }}
type: Opaque
stringData:
  MAIL_PASSWORD: {{ .Values.mail.password }}
{{- end }}
