{{- if and (eq (.Values.minio.enabled | toString) "true") (not .Values.minio.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monitor.minio.secretName" . }}
  labels:
    {{- include "monitor.minio.labels" . | nindent 4 }}
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ .Values.minio.accessKey | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.secretKey | quote }}
{{- end }}
