{{- if .Values.site.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "monitor.site.serviceName" . }}
  labels:
    {{- include "monitor.site.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.site.replicas }}
  selector:
    matchLabels:
      {{- include "monitor.site.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "monitor.site.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: site
          image: "{{ .Values.site.image.repository }}:{{ .Values.site.image.tag }}"
          imagePullPolicy: {{ .Values.site.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: API_BACKEND_HOST
              value: "{{ include "monitor.app.serviceName" . }}"
          volumeMounts:
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d
          resources:
            {{- toYaml .Values.site.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
      volumes:
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}
        - name: nginx-conf
          emptyDir: {}
{{- end }}
