{{- if and (eq (.Values.cnpg.enabled | toString) "true") .Values.cnpg.backup }}
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ include "schnappy.postgres.serviceName" . }}-daily
  labels:
    {{- include "schnappy.postgres.labels" . | nindent 4 }}
spec:
  schedule: "30 1 * * *"
  backupOwnerReference: cluster
  cluster:
    name: {{ include "schnappy.postgres.serviceName" . }}
{{- end }}
