{{- if and (eq (.Values.cnpg.enabled | toString) "true") .Values.cnpg.backup }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cnpg-backup-secrets
  labels:
    {{- include "schnappy.postgres.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames:
      - {{ .Values.cnpg.backupSecret }}
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cnpg-backup-secrets
  labels:
    {{- include "schnappy.postgres.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cnpg-backup-secrets
subjects:
  - kind: ServiceAccount
    name: {{ include "schnappy.postgres.serviceName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
