{{- if and (eq (.Values.kafka.enabled | toString) "true") (not .Values.kafka.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "schnappy.kafka.secretName" . }}
  labels:
    {{- include "schnappy.kafka.labels" . | nindent 4 }}
type: Opaque
data:
  KAFKA_CLUSTER_ID: {{ .Values.kafka.clusterId | b64enc | quote }}
{{- end }}
