{{- if eq (.Values.minio.enabled | toString) "true" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "schnappy.fullname" . }}-minio
  labels:
    {{- include "schnappy.minio.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "schnappy.minio.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "schnappy.minio.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/part-of: schnappy
      annotations:
        backup.velero.io/backup-volumes: data
    spec:
      serviceAccountName: {{ include "schnappy.fullname" . }}-minio
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: minio
          image: {{ .Values.minio.image }}
          imagePullPolicy: IfNotPresent
          command:
            - minio
            - server
            - /data
          ports:
            - containerPort: 9000
              protocol: TCP
              name: s3
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "schnappy.minio.secretName" . }}
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "schnappy.minio.secretName" . }}
                  key: MINIO_ROOT_PASSWORD
          resources:
            {{- toYaml .Values.minio.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: data
              mountPath: /data
            - name: tmp
              mountPath: /tmp
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      volumes:
        - name: tmp
          emptyDir: {}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "schnappy.fullname" . }}-minio
{{- end }}
