{{- if .Values.postgres.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "schnappy.postgres.serviceName" . }}
  labels:
    {{- include "schnappy.postgres.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: tcp-postgres
  selector:
    {{- include "schnappy.postgres.selectorLabels" . | nindent 4 }}
{{- end }}
