{{- if and .Values.redis.password (not .Values.redis.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "schnappy.redis.secretName" . }}
  labels:
    {{- include "schnappy.redis.labels" . | nindent 4 }}
type: Opaque
stringData:
  REDIS_PASSWORD: {{ .Values.redis.password | quote }}
{{- end }}
