apiVersion: v2
name: schnappy-observability
description: Monitoring and logging (ELK, Mimir, Grafana, Alertmanager)
type: application
version: 0.1.1
appVersion: "1.0.0"
keywords:
  - monitoring
  - logging
  - prometheus
  - grafana
icon: https://pmon.dev/favicon.ico
maintainers:
  - name: schnappy
