{{- if ne (.Values.monitor.enabled | toString) "false" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "schnappy.monitor.serviceName" . }}
  labels:
    {{- include "schnappy.monitor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "schnappy.monitor.selectorLabels" . | nindent 4 }}
{{- end }}
