{{- if eq (.Values.envoyGateway.enabled | toString) "true" }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: envoy
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "schnappy.fullname" . }}-gw
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "schnappy.labels" . | nindent 4 }}
spec:
  gatewayClassName: envoy
  listeners:
    - name: http
      protocol: HTTP
      port: 8080
{{- end }}
