{{- if eq (.Values.envoyGateway.enabled | toString) "true" }}
---
# Allow Envoy Gateway (envoy-gateway-system) to reference Services in this namespace
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: {{ include "schnappy.fullname" . }}-envoy-ref
  namespace: {{ .Release.Namespace }}
spec:
  from:
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: {{ .Release.Namespace }}
  to:
    - group: ""
      kind: Service
{{- end }}
