{{- if eq (.Values.envoyGateway.enabled | toString) "true" }}
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: {{ include "schnappy.fullname" . }}-ratelimit
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "schnappy.labels" . | nindent 4 }}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ include "schnappy.fullname" . }}-gw
  rateLimit:
    type: Local
    local:
      rules:
        - clientSelectors:
            - sourceCIDR:
                value: 0.0.0.0/0
                type: Distinct
          limit:
            requests: {{ .Values.envoyGateway.rateLimit.requestsPerSecond | default 50 }}
            unit: Second
{{- end }}
