{{- $root := . -}}
{{- range .Values.games }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "schnappy.fullname" $root }}-{{ .name }}
  labels:
    {{- include "schnappy.labels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .port | default $root.Values.gameDefaults.port }}
      targetPort: {{ .port | default $root.Values.gameDefaults.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "schnappy.selectorLabels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}
{{- end }}
