{{- if and (eq (.Values.gatling.enabled | toString) "true") .Values.vault.secretsEnabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "schnappy.fullname" . }}-gatling
  labels:
    {{- include "schnappy.labels" . | nindent 4 }}
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ include "schnappy.fullname" . }}-gatling
  data:
    - secretKey: CLIENT_SECRET
      remoteRef:
        key: secret/data/schnappy/gatling
        property: client_secret
{{- end }}
