{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "schnappy.fullname" . }}-app
  labels:
    {{- include "schnappy.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "schnappy.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  podMetricsEndpoints:
    - targetPort: 15020
      path: /stats/prometheus
      interval: 15s
{{- end }}
