{{- if and .Values.victoriametrics.enabled (eq (.Values.alertmanager.enabled | toString) "true") -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "schnappy.alertmanager.serviceName" . }}
  labels:
    {{- include "schnappy.alertmanager.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9093
      targetPort: 9093
      protocol: TCP
      name: http
  selector:
    {{- include "schnappy.alertmanager.selectorLabels" . | nindent 4 }}
{{- end }}
