{{- if and .Values.prometheus.enabled (eq (.Values.alertmanager.enabled | toString) "true") -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "schnappy.fullname" . }}-alertmanager
  labels:
    {{- include "schnappy.alertmanager.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.alertmanager.storage.size }}
  {{- if .Values.alertmanager.storage.storageClass }}
  storageClassName: {{ .Values.alertmanager.storage.storageClass }}
  {{- end }}
{{- end }}
