{{- if and .Values.clickhouse.enabled .Values.clickhouse.password (not .Values.clickhouse.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "schnappy.clickhouse.secretName" . }}
  labels:
    {{- include "schnappy.clickhouse.labels" . | nindent 4 }}
type: Opaque
stringData:
  CLICKHOUSE_PASSWORD: {{ .Values.clickhouse.password | quote }}
{{- end }}
