{{- if eq (.Values.elk.enabled | toString) "true" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "schnappy.elasticsearch.serviceName" . }}
  labels:
    {{- include "schnappy.elasticsearch.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9200
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "schnappy.elasticsearch.selectorLabels" . | nindent 4 }}
{{- end }}
