{{- if eq (.Values.elk.enabled | toString) "true" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "schnappy.fullname" . }}-fluentbit-config
  labels:
    {{- include "schnappy.fluentbit.labels" . | nindent 4 }}
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush             5
        Log_Level         warn
        Parsers_File      /fluent-bit/etc/parsers.conf
        storage.path      /fluent-bit/db/
        storage.sync      normal
        storage.checksum  off

    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            cri
        DB                /fluent-bit/db/tail.db
        Mem_Buf_Limit     64MB
        storage.type      filesystem
        Skip_Long_Lines   On
        Refresh_Interval  10
        Rotate_Wait       5
        Exclude_Path      /var/log/containers/*k6-*

    [FILTER]
        Name              kubernetes
        Match             kube.*
        Kube_URL          https://kubernetes.default.svc:443
        Kube_CA_File      /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File   /var/run/secrets/kubernetes.io/serviceaccount/token
        Merge_Log         On
        Merge_Log_Key     log_parsed
        K8S-Logging.Parser On
        Annotations       Off
        Labels            On
        Replace_Dots      On

    [FILTER]
        Name              grep
        Match             kube.*
        Exclude           $kubernetes['container_name'] fluent-bit

    [OUTPUT]
        Name              es
        Match             kube.*
        Host              {{ include "schnappy.elasticsearch.serviceName" . }}.{{ .Release.Namespace }}.svc
        Port              9200
        HTTP_User         elastic
        HTTP_Passwd       ${ELASTICSEARCH_PASSWORD}
        Index             podlogs
        Logstash_Format   On
        Logstash_Prefix   podlogs
        Suppress_Type_Name On
        tls               Off
        Retry_Limit       5
        Buffer_Size       False
        Generate_ID       Off
        Workers           2
        Trace_Error       On

  parsers.conf: |
    [PARSER]
        Name        cri
        Format      regex
        Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<_p>[^ ]*) (?<log>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
{{- end }}
