{{- if .Values.grafana.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "schnappy.fullname" . }}-grafana-datasources
  labels:
    {{- include "schnappy.grafana.labels" . | nindent 4 }}
data:
  datasources.yml: |
    apiVersion: 1
    deleteDatasources:
      - name: Prometheus
        orgId: 1
    datasources:
      - name: VictoriaMetrics
        type: prometheus
        uid: prometheus
        access: proxy
        url: http://{{ include "schnappy.victoriametrics.serviceName" . }}:8428
        isDefault: true
        editable: false
{{- end }}
