{{- if .Values.grafana.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "schnappy.fullname" . }}-grafana
  labels:
    {{- include "schnappy.grafana.labels" . | nindent 4 }}
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
    - port: {{ .Values.grafana.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "schnappy.grafana.selectorLabels" . | nindent 4 }}
{{- end }}
