{{- if .Values.grafana.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "schnappy.fullname" . }}-grafana-datasources
  labels:
    {{- include "schnappy.grafana.labels" . | nindent 4 }}
data:
  datasources.yml: |
    apiVersion: 1
    deleteDatasources:
      - name: Prometheus
        orgId: 1
      - name: VictoriaMetrics
        orgId: 1
    datasources:
      - name: Mimir
        type: prometheus
        uid: prometheus
        access: proxy
        url: http://{{ include "schnappy.fullname" . }}-mimir:9009/prometheus
        isDefault: true
        editable: false
        jsonData:
          prometheusType: Mimir
{{- end }}
