{{- if eq (.Values.elk.enabled | toString) "true" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "schnappy.fullname" . }}-kibana-config
  labels:
    {{- include "schnappy.kibana.labels" . | nindent 4 }}
data:
  kibana.yml: |
    server.host: "::"
    server.name: "kibana"
    elasticsearch.hosts: ["http://{{ include "schnappy.elasticsearch.serviceName" . }}:9200"]
    xpack.encryptedSavedObjects.encryptionKey: "a]3{W`G:kj`m2~dEd;'L&Cx:f4{!&3fhMn(+Y-change-me"
    telemetry.enabled: false
{{- $kibanaHost := .Values.elk.kibana.host | default .Values.elk.kibana.ingress.host | default "" }}
{{- if $kibanaHost }}
    server.publicBaseUrl: "https://{{ $kibanaHost }}"
{{- end }}
{{- end }}
