{{- if .Values.openobserve.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "schnappy.openobserve.serviceName" . }}
  labels:
    {{- include "schnappy.openobserve.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - { name: http, port: 5080, targetPort: 5080, protocol: TCP }
  selector:
    {{- include "schnappy.openobserve.selectorLabels" . | nindent 4 }}
{{- end }}
