{{- if and .Values.reports .Values.reports.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "schnappy.fullname" . }}-reports
  labels:
    {{- include "schnappy.reports.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "schnappy.reports.selectorLabels" . | nindent 4 }}
{{- end }}
