{{- if eq (.Values.tempo.enabled | toString) "true" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "schnappy.fullname" . }}-tempo
  labels:
    {{- include "schnappy.tempo.labels" . | nindent 4 }}
{{- end }}
