{{- if .Values.victoriametrics.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "schnappy.fullname" . }}-victoriametrics-config
  labels:
    {{- include "schnappy.victoriametrics.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.victoriametrics.scrapeInterval }}

    scrape_configs:
      - job_name: 'victoriametrics'
        static_configs:
          - targets: ['localhost:8428']

      - job_name: 'schnappy-app'
        metrics_path: '/api/actuator/prometheus'
        static_configs:
          - targets: ['{{ include "schnappy.monitor.serviceName" . }}:{{ .Values.app.service.port }}']
      {{- if .Values.victoriametrics.vault.enabled }}
      - job_name: 'vault'
        metrics_path: '/v1/sys/metrics'
        params:
          format: ['prometheus']
        scheme: https
        tls_config:
          ca_file: /vault/tls/ca.crt
        bearer_token_file: /var/run/secrets/vault-metrics/token
        static_configs:
          - targets: ['vault.vault.svc:8200']
      {{- end }}
      {{- if eq (.Values.kubeStateMetrics.enabled | toString) "true" }}
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['{{ include "schnappy.kubeStateMetrics.serviceName" . }}:8080']
      {{- end }}
      {{- if eq (.Values.victoriametrics.woodpecker.enabled | toString) "true" }}
      - job_name: 'woodpecker'
        bearer_token: 'metrics'
        static_configs:
          - targets: ['woodpecker-server-0.woodpecker-server-headless.woodpecker.svc:9001']
      {{- end }}
      {{- if eq (.Values.victoriametrics.forgejo.enabled | toString) "true" }}
      - job_name: 'forgejo'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['forgejo-http.forgejo.svc:3000']
      {{- end }}
{{- end }}
