{{- if and (eq (.Values.keycloak.enabled | toString) "true") (eq (.Values.keycloak.ingress.enabled | toString) "true") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "schnappy.fullname" . }}-keycloak
  labels:
    {{- include "schnappy.keycloak.labels" . | nindent 4 }}
  {{- if and .Values.keycloak.ingress.tls .Values.keycloak.ingress.tls.enabled }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.keycloak.ingress.tls.clusterIssuer | default "letsencrypt-dns" }}
  {{- end }}
spec:
  {{- if .Values.keycloak.ingress.className }}
  ingressClassName: {{ .Values.keycloak.ingress.className }}
  {{- end }}
  {{- if and .Values.keycloak.ingress.tls .Values.keycloak.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.keycloak.ingress.host }}
      {{- if .Values.keycloak.ingress.tls.secretName }}
      secretName: {{ .Values.keycloak.ingress.tls.secretName }}
      {{- end }}
  {{- end }}
  rules:
    - {{ if .Values.keycloak.ingress.host }}host: {{ .Values.keycloak.ingress.host }}{{ end }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "schnappy.keycloak.serviceName" . }}
                port:
                  number: 8080
{{- end }}
