{{- if .Values.gateway.enabled }}
{{- $fn := include "schnappy.fullname" . }}
# Single wildcard certificate for all *.pmon.dev hosts
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pmon-dev-wildcard-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: pmon-dev-wildcard-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
    - "*.pmon.dev"
    - pmon.dev
{{- end }}
