{{- $ns := .Release.Namespace }}
{{- $fullname := include "schnappy.fullname" . }}
{{- range $sa := list "monitor" "admin" "chat" "chess" "site" "postgres" "redis" "kafka" "scylla" "minio" "keycloak" "elasticsearch" "kibana" "fluentbit" "victoriametrics" "alertmanager" "grafana" "reports" "sonarqube" "sonarqube-postgres" "apt-cache" "kube-state-metrics" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $fullname }}-{{ $sa }}
  namespace: {{ $ns }}
  labels:
    app.kubernetes.io/part-of: schnappy
    app.kubernetes.io/component: {{ $sa }}
{{- end }}
