{{- if .Values.vault.secretsEnabled }}
{{- if eq (.Values.sonarqube.enabled | toString) "true" }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "schnappy.sonarqube.secretName" . }}
  labels:
    {{- include "schnappy.sonarqube.labels" . | nindent 4 }}
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ include "schnappy.sonarqube.secretName" . }}
  data:
    - secretKey: SONARQUBE_POSTGRES_PASSWORD
      remoteRef:
        key: secret/data/schnappy/sonarqube
        property: postgres_password
    - secretKey: SONARQUBE_ADMIN_PASSWORD
      remoteRef:
        key: secret/data/schnappy/sonarqube
        property: admin_password
    - secretKey: SONARQUBE_TOKEN
      remoteRef:
        key: secret/data/schnappy/sonarqube
        property: token
{{- end }}
{{- end }}
