{{- if and (eq (.Values.sonarqube.enabled | toString) "true") .Values.sonarqube.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "schnappy.fullname" . }}-sonarqube
  labels:
    {{- include "schnappy.sonarqube.labels" . | nindent 4 }}
  {{- if and .Values.sonarqube.ingress.tls .Values.sonarqube.ingress.tls.enabled }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.sonarqube.ingress.tls.clusterIssuer | default "letsencrypt-prod" }}
  {{- end }}
spec:
  {{- if .Values.sonarqube.ingress.className }}
  ingressClassName: {{ .Values.sonarqube.ingress.className }}
  {{- end }}
  {{- if and .Values.sonarqube.ingress.tls .Values.sonarqube.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.sonarqube.ingress.host }}
      {{- if .Values.sonarqube.ingress.tls.secretName }}
      secretName: {{ .Values.sonarqube.ingress.tls.secretName }}
      {{- end }}
  {{- end }}
  rules:
    - {{ if .Values.sonarqube.ingress.host }}host: {{ .Values.sonarqube.ingress.host }}{{ end }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "schnappy.sonarqube.serviceName" . }}
                port:
                  number: {{ .Values.sonarqube.service.port }}
{{- end }}
